// Metadata only. Each writeup is a fully self-contained .html file
// (images embedded inside it) generated by writeup-generator.html and
// saved into public/writeups/<file>.
//
// To add a new writeup:
//   1. Open writeup-generator.html, fill it in, attach images, click Generate.
//   2. Save the downloaded .html file into public/writeups/
//   3. Paste the entry the tool gives you below, under the right category.

const writeupsIndex = {
  forensics: [
    // { file: "memory-dump-mayhem.html", title: "Memory Dump Mayhem", tags: ["volatility"], date: "2026-04-01" },
  ],
  web: [
    {
      file: "encrypt-responsibly.html",
      title: "Encrypt Responsibly",
      tags: ["web", "crypto", "security"],
      date: "2026-09-28",
    }
  ],
  osint: [
    {
      file: "case-of-the-overconfident-consultant.html",
      title: "Case of the Overconfident Consultant",
      tags: ["osint"],
      date: "2026-09-27",
    },
  ],
  mobile: [],
  "reverse-engineering": [],
  cryptography: [],
};

// PUBLIC_URL resolves to your subpath automatically (e.g. "/zyrvex-blog" in
// production, from the "homepage" field in package.json), so this always
// points at the right place whether you're local or deployed.
export function writeupUrl(file) {
  return `${process.env.PUBLIC_URL}/writeups/${file}`;
}

export default writeupsIndex;